# Generated by Django 5.0.4 on 2024-04-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_agendamento', models.TextField(blank=True, max_length=255)),
                ('especialidade_agendamento', models.TextField(blank=True, max_length=255)),
                ('medico_agendamento', models.TextField(blank=True, max_length=255)),
                ('data_agendamento', models.DateField(blank=True)),
                ('hora_agendamento', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('cpf', models.TextField(max_length=11)),
                ('telefone', models.TextField(max_length=14)),
                ('idade', models.DateField()),
                ('senha', models.CharField(max_length=20)),
            ],
        ),
    ]
